#include "tarot_runtime.h"

void tarot_runtime_init(tarot_runtime_t *runtime, int64_t now_us) {
    if (!runtime) return;
    *runtime = (tarot_runtime_t) {
        .last_input_us = now_us,
        .next_battery_refresh_us = now_us + TAROT_BATTERY_REFRESH_US,
        .idle_state = TAROT_IDLE_ACTIVE,
    };
}

tarot_idle_state_t tarot_runtime_update_idle(tarot_runtime_t *runtime, int64_t now_us) {
    if (!runtime) return TAROT_IDLE_ACTIVE;
    int64_t idle_us = now_us - runtime->last_input_us;
    runtime->idle_state = idle_us >= TAROT_OFF_AFTER_US ? TAROT_IDLE_OFF
                        : idle_us >= TAROT_DIM_AFTER_US ? TAROT_IDLE_DIMMED
                                                       : TAROT_IDLE_ACTIVE;
    return runtime->idle_state;
}

bool tarot_runtime_note_input(tarot_runtime_t *runtime, int64_t now_us,
                              bool is_press, bool *woke_display) {
    if (woke_display) *woke_display = false;
    if (!runtime) return false;

    bool was_off = runtime->idle_state == TAROT_IDLE_OFF;
    runtime->last_input_us = now_us;
    runtime->idle_state = TAROT_IDLE_ACTIVE;
    if (was_off) {
        /* Suppress every event generated by this physical interaction. The
         * next PRESS marks the beginning of a new interaction; its later
         * CLICK/LONG event may then be dispatched normally. */
        runtime->suppress_until_next_press = true;
        if (woke_display) *woke_display = true;
        return false;
    }
    if (runtime->suppress_until_next_press) {
        if (is_press) runtime->suppress_until_next_press = false;
        return false;
    }
    return !is_press;
}

bool tarot_runtime_battery_refresh_due(tarot_runtime_t *runtime, int64_t now_us) {
    if (!runtime || now_us < runtime->next_battery_refresh_us) return false;
    runtime->next_battery_refresh_us = now_us + TAROT_BATTERY_REFRESH_US;
    return true;
}
