#!/usr/bin/env python3
"""Convert the transparent slot atlas into shared large/small LVGL RGB565 sprites.

Requires Pillow. Symbols retain their proportions. Const arrays stay in Flash.
"""
from pathlib import Path
from PIL import Image

ROOT = Path(__file__).resolve().parents[1]
NAMES = ('cherry', 'lemon', 'bar', 'bell', 'plum', 'seven')
SIZES = (('', 48, 64, 'ARCADE_SLOT_SYMBOLS'),
         ('small-', 32, 36, 'ARCADE_SLOT_SMALL_SYMBOLS'))


def convert():
    atlas = Image.open(ROOT / 'assets/images/slot-classic-atlas.png').convert('RGBA')
    assert atlas.size == (1536, 1024), atlas.size
    code = ['/* Generated by tools/convert_slot_symbols.py; do not hand edit. */',
            '#include "slot_symbols.h"', '']
    total = 0
    for prefix, width, height, table in SIZES:
        previews = []
        for index, name in enumerate(NAMES):
            x, y = index % 3 * 512, index // 3 * 512
            cell = atlas.crop((x, y, x + 512, y + 512))
            alpha = cell.getchannel('A')
            assert alpha.getextrema()[0] == 0, 'Atlas requires transparent gutters'
            bbox = alpha.point(lambda a: 255 if a > 16 else 0).getbbox()
            assert bbox is not None
            icon = cell.crop(bbox)
            icon.thumbnail((width - 2, height - 4), Image.Resampling.LANCZOS)
            tile = Image.new('RGBA', (width, height), (247, 241, 227, 255))
            tile.alpha_composite(icon, ((width - icon.width) // 2, (height - icon.height) // 2))
            tile = tile.convert('RGB')
            tile.save(ROOT / f'assets/images/slot-{prefix}{name}.png')
            previews.append(tile)
            data = []
            for r, g, b in tile.getdata():
                v = (r >> 3) << 11 | (g >> 2) << 5 | (b >> 3)
                data.extend((v & 255, v >> 8))
            assert len(data) == width * height * 2
            total += len(data)
            identifier = f'slot_{prefix.replace("-", "_")}{name}_pixels'
            code.append(f'static const uint8_t {identifier}[{len(data)}] __attribute__((aligned(4))) = {{')
            for i in range(0, len(data), 24):
                code.append('    ' + ','.join(f'0x{x:02x}' for x in data[i:i + 24]) + ',')
            code.extend(('};', ''))
        code.append(f'const lv_image_dsc_t {table}[SLOT_SYMBOL_COUNT] = {{')
        for name in NAMES:
            identifier = f'slot_{prefix.replace("-", "_")}{name}_pixels'
            code.append('    {.header={.magic=LV_IMAGE_HEADER_MAGIC, .cf=LV_COLOR_FORMAT_RGB565, '
                        f'.w={width}, .h={height}, .stride={width * 2}' + '}, '
                        f'.data_size={width * height * 2}, .data={identifier}' + '},')
        code.append('};\n')
        preview = Image.new('RGB', (width * 6, height), (247, 241, 227))
        for i, tile in enumerate(previews):
            preview.paste(tile, (i * width, 0))
        preview.save(ROOT / f'assets/images/slot-symbols-{prefix}native.png')
    (ROOT / 'assets/images/slot_symbols.c').write_text('\n'.join(code))
    print(f'Twelve shared sprites: {total:,} bytes RGB565 in Flash')


if __name__ == '__main__':
    convert()
